Portfolio/Areas/Admin/Controllers/ExperienceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portfolio.DataAccess.Repository.IRepository;
using Portfolio.Models;
using Portfolio.Models.ViewModels;
using Utility;

namespace Portfolio.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Roles = AppConstant.Role_Admin)]
    public class ExperienceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ExperienceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Experience> experience = _unitOfWork.Experience
                .GetAll(includeProperties: "Owner").ToList();
            return View(experience);
        }



        public IActionResult Upsert(int? id)
        {
            ExperienceOwnerVM experienceOwnerVM = new()
            {
                OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }),
                Experience = new Experience()
            };
            if (id == null || id == 0)
            {
                //Create
                return View(experienceOwnerVM);
            }
            else
            {
                //Update
                experienceOwnerVM.Experience = _unitOfWork.Experience.Get(p => p.Id == id);

                return View(experienceOwnerVM);
            }
        }


        [HttpPost]
        public IActionResult Upsert(ExperienceOwnerVM experienceOwnerVM)
        {
            if (ModelState.IsValid)
            {
                if (experienceOwnerVM.Experience.Id == 0)
                {
                    _unitOfWork.Experience.Add(experienceOwnerVM.Experience);
                    TempData["success"] = "Education Created Successfully";
                }
                else
                {
                    _unitOfWork.Experience.Update(experienceOwnerVM.Experience);
                    TempData["success"] = "Education Updated Successfully";
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                experienceOwnerVM.OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });
            
            return View(experienceOwnerVM);
            }
        }


        #region API CALLS     
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var experienceToBeDeleted = _unitOfWork.Experience.Get(c => c.Id == id);
            if (experienceToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _unitOfWork.Experience.Remove(experienceToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

Portfolio/Areas/Admin/Views/Experience/Index.cshtml
@model List<Experience>

<div class="card shadow border-0 my-4">
    <div class="card-header bg-dark bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h3 class="text-primary py-2">Experiences List</h3>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-12 text-end">
                <a asp-controller="Experience" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> Create New Experience
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th class="text-center">Job Title</th>
                    <th class="text-center">Company</th>
                    <th class="text-center">Start Job</th>
                    <th class="text-center">End Job</th>
                    <th class="text-center"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var experience in Model)
                {
                    <tr>
                        <td class="text-center">@experience.JobTitle</td>
                        <td class="text-center">@experience.Company</td>
                        <td class="text-center">@experience.StartJob</td>
                        <td class="text-center">@experience.EndJob</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Experience" asp-action="Upsert" asp-route-id="@experience.Id" class="btn btn-secondary mx-2">
                                    <i class="bi bi-pencil-square" title="Edit"></i>
                                </a>
                                <a class="btn btn-primary mx-2" onclick="confirmDelete(@experience.Id)">

                                    <i class="bi bi-trash-fill" title="Delete"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script src="~/js/experience.js"></script>
}

Portfolio/Areas/Admin/Views/Experience/Upsert.cshtml
@model ExperienceOwnerVM

<div class="card shadow border-0 my-4">
    <div class="card-header bg-dark bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h3 class="text-primary py-2">@(Model.Experience.Id != 0 ? "Update" : "Create") Experience</h3>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row">
            <input asp-for="Experience.Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-floating mb-3">
                            <input asp-for="Experience.JobTitle" class="form-control border-0 shadow" placeholder="" />
                            <label asp-for="Experience.JobTitle" class="form-label"></label>
                            <span asp-validation-for="Experience.JobTitle" class="text-danger"></span>
                        </div>
                        <div class="form-floating mb-3">
                            <input asp-for="Experience.Company" class="form-control border-0 shadow" placeholder="" />
                            <label asp-for="Experience.Company" class="form-label text-muted"></label>
                            <span asp-validation-for="Experience.Company" class=" text-danger"></span>
                        </div>
                        <div class="form-floating mb-3">
                            <input asp-for="Experience.StartJob" class="form-control border-0 shadow" placeholder="" />
                            <label asp-for="Experience.StartJob" class="form-label text-muted"></label>
                            <span asp-validation-for="Experience.StartJob" class=" text-danger"></span>
                        </div>
                        <div class="form-floating mb-3">
                            <input asp-for="Experience.EndJob" class="form-control border-0 shadow" placeholder="" />
                            <label asp-for="Experience.EndJob" class="form-label text-muted"></label>
                            <span asp-validation-for="Experience.EndJob" class=" text-danger"></span>
                        </div>
                        <div class="form-floating mb-3">
                            <input asp-for="Experience.Description" class="form-control border-0 shadow" placeholder="" />
                            <label asp-for="Experience.Description" class="form-label text-muted"></label>
                            <span asp-validation-for="Experience.Description" class=" text-danger"></span>
                        </div>

                        <div class="form-floating mb-3">
                            <select asp-for="Experience.OwnerId" asp-items="@Model.OwnerList" class="form-select border-0 shadow">
                                <option disabled selected>--Select Owner--</option>
                            </select>
                            <label asp-for="Experience.OwnerId" class="text-muted"></label>
                            <span asp-validation-for="Experience.OwnerId" class="text-danger"></span>
                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Experience.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Experience" asp-action="Index" class="btn btn-outline-secondary border form-control">
                                    Back To List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}