Portfolio/Areas/Admin/Controllers/EducationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portfolio.DataAccess.Repository.IRepository;
using Portfolio.Models;
using Portfolio.Models.ViewModels;
using Utility;

namespace Portfolio.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Roles = AppConstant.Role_Admin)]
    public class EducationController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public EducationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {

            List<Education> education = _unitOfWork.Education.GetAll(includeProperties: "Owner").ToList();

            return View(education);
        }



        public IActionResult Upsert(int? id)
        {
            EducationOwnerVM educationOwnerVM = new()
            {
                OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }),
                Education = new Education()
            };
            if (id == null || id == 0)
            {
                //Create
                return View(educationOwnerVM);
            }
            else
            {
                //Update
                educationOwnerVM.Education = _unitOfWork.Education.Get(p => p.Id == id);

                return View(educationOwnerVM);
            }
        }


        [HttpPost]
        public IActionResult Upsert(EducationOwnerVM educationVM)
        {
            if (ModelState.IsValid)
            {
                if (educationVM.Education.Id == 0)
                {
                    _unitOfWork.Education.Add(educationVM.Education);
                    TempData["success"] = "Education Created Successfully";
                }
                else
                {
                    _unitOfWork.Education.Update(educationVM.Education);
                    TempData["success"] = "Education Updated Successfully";
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                educationVM.OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });
                return View(educationVM);
            }
        }


        #region API CALLS     
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var educationToBeDeleted = _unitOfWork.Education.Get(c => c.Id == id);
            if (educationToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _unitOfWork.Education.Remove(educationToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

Portfolio/Areas/Admin/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portfolio.DataAccess.Repository.IRepository;
using Portfolio.Models;
using Portfolio.Models.ViewModels;
using Utility;

namespace Portfolio.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Roles = AppConstant.Role_Admin)]
    public class ProjectController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProjectController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {

            List<Project> project = _unitOfWork.Project.GetAll(includeProperties: "Owner").ToList();

            return View(project);
        }



        public IActionResult Upsert(int? id)
        {
            ProjectOwnerVM projectOwnerVM = new()
            {
                OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }),
                Project = new Project()
            };
            if (id == null || id == 0)
            {
                //Create
                return View(projectOwnerVM);
            }
            else
            {
                //Update
                projectOwnerVM.Project = _unitOfWork.Project
                    .Get(p => p.Id == id, includeProperties: "ProjectImages");

                return View(projectOwnerVM);
            }
        }


        [HttpPost]
        public IActionResult Upsert(ProjectOwnerVM projectOwnerVM, List<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                if (projectOwnerVM.Project.Id == 0)
                {
                    _unitOfWork.Project.Add(projectOwnerVM.Project);
                    TempData["success"] = "Education Created Successfully";
                }
                else
                {
                    _unitOfWork.Project.Update(projectOwnerVM.Project);
                    TempData["success"] = "Education Updated Successfully";
                }
                _unitOfWork.Save();

                // Setting Images 
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (files != null)
                {
                    foreach (var file in files)
                    {
                        //Rename Image
                        string fileName = $"{Guid.NewGuid().ToString()}" +
                            $"{Path.GetExtension(file.FileName)}";

                        // path diractory
                        string productPath = @"images/project/project-" + projectOwnerVM.Project.Id;
                        string finalPath = Path.Combine(wwwRootPath, productPath);

                        if (!Directory.Exists(finalPath))
                        {
                            Directory.CreateDirectory(finalPath);
                        }

                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }

                        ProjectImage projectImage = new()
                        {
                            ImageUrl = $"/{productPath}/{fileName}",
                            ProjectId = projectOwnerVM.Project.Id,
                        };

                        if (projectOwnerVM.Project.ProjectImages == null)
                        {
                            projectOwnerVM.Project.ProjectImages = new List<ProjectImage>();
                        }

                        projectOwnerVM.Project.ProjectImages.Add(projectImage);
                    }
                    _unitOfWork.Project.Update(projectOwnerVM.Project);
                    _unitOfWork.Save();
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                projectOwnerVM.OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });
                return View(projectOwnerVM);
            }
        }


        public IActionResult DeleteImage(int imageId)
        {
            var imageToBeDeleted = _unitOfWork.ProjectImage.Get(i => i.Id == imageId);
            var projectId = imageToBeDeleted.ProjectId;
            if (imageToBeDeleted != null)
            {
                if (!string.IsNullOrEmpty(imageToBeDeleted.ImageUrl))
                {
                    var oldImagePath =
                        Path.Combine(_webHostEnvironment.WebRootPath,
                        imageToBeDeleted.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork.ProjectImage.Remove(imageToBeDeleted);
                _unitOfWork.Save();

                TempData["success"] = "Image Deleted Successfully";
            }
            return RedirectToAction(nameof(Upsert), new { id = projectId });
        }


        #region API CALLS     
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var projectToBeDeleted = _unitOfWork.Project.Get(c => c.Id == id);
            if (projectToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }

            // path diractory
            string projectPath = @"images/project/project-" + id;
            string finalPath = Path.Combine(_webHostEnvironment.WebRootPath, projectPath);

            if (Directory.Exists(finalPath))
            {
                string[] filePaths = Directory.GetFiles(finalPath);
                foreach (string filePath in filePaths)
                {
                    System.IO.File.Delete(filePath);
                }
                Directory.Delete(finalPath);
            }
            _unitOfWork.Project.Remove(projectToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

Portfolio/Areas/Admin/Controllers/SkillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portfolio.DataAccess.Repository.IRepository;
using Portfolio.Models;
using Portfolio.Models.ViewModels;
using Utility;

namespace Portfolio.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Roles = AppConstant.Role_Admin)]
    public class SkillController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public SkillController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {

            List<Skill> skill = _unitOfWork.Skill.GetAll(includeProperties: "Owner").ToList();

            return View(skill);
        }



        public IActionResult Upsert(int? id)
        {
            SkillOwnerVM skillOwnerVM = new()
            {
                OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }),
                Skill = new Skill()
            };
            if (id == null || id == 0)
            {
                //Create
                return View(skillOwnerVM);
            }
            else
            {
                //Update
                skillOwnerVM.Skill = _unitOfWork.Skill.Get(p => p.Id == id);

                return View(skillOwnerVM);
            }
        }


        [HttpPost]
        public IActionResult Upsert(SkillOwnerVM skillOwnerVM)
        {
            if (ModelState.IsValid)
            {
                if (skillOwnerVM.Skill.Id == 0)
                {
                    _unitOfWork.Skill.Add(skillOwnerVM.Skill);
                    TempData["success"] = "Skill Created Successfully";
                }
                else
                {
                    _unitOfWork.Skill.Update(skillOwnerVM.Skill);
                    TempData["success"] = "Skill Updated Successfully";
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                skillOwnerVM.OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });
                
                return View(skillOwnerVM);
            }
        }


        #region API CALLS     
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var skillToBeDeleted = _unitOfWork.Skill.Get(c => c.Id == id);
            if (skillToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _unitOfWork.Skill.Remove(skillToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

Portfolio/Areas/Admin/Controllers/SocialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portfolio.DataAccess.Repository.IRepository;
using Portfolio.Models;
using Portfolio.Models.ViewModels;
using Utility;

namespace Portfolio.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Roles = AppConstant.Role_Admin)]
    public class SocialController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public SocialController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {

            List<Social> social = _unitOfWork.Social.GetAll(includeProperties: "Owner").ToList();

            return View(social);
        }



        public IActionResult Upsert(int? id)
        {
            SocialOwnerVM socialOwnerVM = new()
            {
                OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }),
                Social = new Social()
            };
            if (id == null || id == 0)
            {
                //Create
                return View(socialOwnerVM);
            }
            else
            {
                //Update
                socialOwnerVM.Social = _unitOfWork.Social.Get(p => p.Id == id);

                return View(socialOwnerVM);
            }
        }


        [HttpPost]
        public IActionResult Upsert(SocialOwnerVM socialOwnerVM)
        {
            if (ModelState.IsValid)
            {
                if (socialOwnerVM.Social.Id == 0)
                {
                    _unitOfWork.Social.Add(socialOwnerVM.Social);
                    TempData["success"] = "Social Created Successfully";
                }
                else
                {
                    _unitOfWork.Social.Update(socialOwnerVM.Social);
                    TempData["success"] = "Social Updated Successfully";
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                socialOwnerVM.OwnerList = _unitOfWork.Owner.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });
                
                return View(socialOwnerVM);
            }
        }


        #region API CALLS     
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var socialToBeDeleted = _unitOfWork.Social.Get(c => c.Id == id);
            if (socialToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _unitOfWork.Social.Remove(socialToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

Portfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Ahmad Aslan Portfolio" name="keywords">
    <meta content="Ahmad Aslan Portfolio Backend .net Develober asp MVC " name="description">
    <title>@ViewData["Title"] Ahmad Aslan</title>


    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:300;400;600;700;800&display=swap" rel="stylesheet">

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/lib/slick/slick.css">
    <link rel="stylesheet" href="~/lib/slick/slick-theme.css" />
    <link rel="stylesheet" href="~/lib/lightbox/css/lightbox.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <!-- Template Stylesheet -->
    <link rel="stylesheet" href="~/css/style.css">

</head>
<body data-spy="scroll" data-target=".navbar" data-offset="51">
    <div class="wrapper">
        <div class="sidebar">
            <div class="sidebar-content">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">Ahmad Aslan</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="nav navbar-nav">
                            @if (User.IsInRole(AppConstant.Role_Admin))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Public" asp-controller="Home" asp-action="Index">Home<i class="fa fa-home"></i></a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" href="#header">Home<i class="fa fa-home"></i></a>
                                </li>
                            }                           
                            <li class="nav-item">
                                <a class="nav-link" href="#about">About<i class="fa fa-address-card"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#experience">Experience<i class="fa fa-star"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#portfolio">Portfolio<i class="fa fa-file-archive"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#contact">Contact<i class="fa fa-envelope"></i></a>
                            </li>
                            @if (User.IsInRole(AppConstant.Role_Admin))
                            {
                                <li class="dropdown nav-item">
                                    <a class="nav-link dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Manage Content<i class="fa fa-tasks" aria-hidden="true"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item nav-item" asp-area="Admin" asp-controller="Education" asp-action="Index">Education</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Experience" asp-action="Index">Experience</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Project" asp-action="Index">Project</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Skill" asp-action="Index">Skill</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Social" asp-action="Index">Social</a>
                                    </div>
                                </li>
                            }
                            <partial name="_LoginPartial" />
                        </ul>

                    </div>
                </nav>
            </div>
        </div>

        <div class="content">
            <main role="main">
                <partial name="_Notification" class="text-dark text-center" />
                @RenderBody()
            </main>
        </div>

    </div>

    <!-- Back to Top -->
    <a href="#" class="back-to-top"><i class="fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/slick/slick.min.js"></script>
    <script src="lib/typed/typed.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/isotope/isotope.pkgd.min.js"></script>
    <script src="lib/lightbox/js/lightbox.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Portfolio/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script>
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script>
        toastr.error('@TempData["error"]');
    </script>
}